#Aufgabe 3
##a)
#summary()
#library(psych)
#describe()
##b)
#factor(x = character(), levels, labels = levels, ordered = is.ordered(x))
#summary()
##c)
#chisq.test(x1,x2) 
##d)
#Cochran-Mantel-Haenszel Test
#cmh.test()
##e)
#factor_daten<- factor(daten, order = TRUE, levels =c('niedrig', 'mittel', 'hoch')))
#summary(factor_daten)
##f)
#boxplot()
#hist()
#barplot()
#ggplot()